HW9/Maktab50/djangol1/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('home/', views.show_all_posts, name='show-all-posts'),
    path('create/', views.create_post, name='create-post'),
    path('create-category/', views.CreateCategory.as_view(), name='create-category'),
    path('update-category/<int:pk>', views.UpdateCategory.as_view(), name='update-category'),
    path('like-post/<int:id>', views.like_post, name='like-post'),
    path('edit/<int:pk>', views.edit_post, name='edit'),
    path('post/<int:pk>', views.ViewPost.as_view(), name='detail'),
    path('category/<slug:category_slug>/', views.FilterPostByCategory.as_view(), name='post-by-category'),
]

HW9/Maktab50/djangol1/djangol1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HW9/Maktab50/djangol1/inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'
urlpatterns = [
    path('product', views.ListProductView.as_view(), name='list')
]

HW9/Maktab50/djangol1/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/edit/', views.EditUserProfile.as_view(), name='edit-profile'),
]

HW9/Maktab50/djangol1/blog/models.py
from django.db import models


class Post(models.Model):
    created_data = models.DateTimeField(verbose_name='تاریخ ایجاد', auto_now_add=True)
    title = models.CharField(verbose_name='عنوان پست', max_length=100)
    creator = models.ForeignKey('auth.User', verbose_name='کاربر', on_delete=models.PROTECT)
    content = models.TextField(verbose_name='متن')
    intro_image = models.ImageField(verbose_name='عکس مقدمه پست', blank=True, null=True)
    likes = models.IntegerField(default=0)
    categories = models.ManyToManyField('blog.Category')

    def __str__(self):
        return f'{self.title}'


class Category(models.Model):
    """
    Categories for postsf
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=20, unique=True, null=True, blank=False)

    def __str__(self):
        return self.name

HW9/Maktab50/djangol1/blog/forms.py
from django import forms
from . import models


class CalcForm(forms.Form):
    pass


class PostForm(forms.ModelForm):
    """
    Model form for post model
    """

    class Meta:
        model = models.Post
        fields = [
            'title',
            'content',
            'intro_image',
            'categories',
        ]

HW9/Maktab50/djangol1/blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from . import models, forms


def show_all_posts(request):
    if request.user.is_authenticated:
        my_posts = models.Post.objects.filter(creator=request.user)
        other_posts = models.Post.objects.exclude(creator=request.user)
    else:
        my_posts = models.Post.objects.all()
        other_posts = []
    return render(
        request=request,
        context={'object_list': my_posts,
                 'object_list_2': other_posts,
                 'page_title': 'Show all posts',
                 },
        template_name='blog/all_posts.html'
    )


@login_required
def create_post(request):
    """
    Creates a post
    """
    if not request.user.has_perm('blog.add_post'):
        raise PermissionDenied('Access denied.')

    form_instance = forms.PostForm()

    if request.method == 'POST':
        form_instance = forms.PostForm(data=request.POST)
        if form_instance.is_valid():
            form_instance.instance.creator = request.user
            form_instance.save()
            return redirect('blog:show-all-posts')

    return render(request=request,
                  context={'form': form_instance,
                           'page_title': 'Create new post'},
                  template_name='blog/post_form.html'
                  )


def edit_post(request, pk):
    """
    Edit a single post
    """
    post_instance = get_object_or_404(klass=models.Post, pk=pk)
    if not post_instance.creator == request.user:
        return HttpResponseForbidden('Access denied')
    if not request.user.has_perm('blog.change_post'):
        raise PermissionDenied('Access denied.')
    if request.method == 'POST':
        form_instance = forms.PostForm(instance=post_instance, data=request.POST, files=request.FILES)
        if form_instance.is_valid():
            form_instance.save()
            messages.success(request, 'Saved successfully')
            return redirect('blog:show-all-posts')
    else:
        # The Get method
        form_instance = forms.PostForm(instance=post_instance)
        return render(
            request,
            context={
                'form': form_instance,
                'page_title': f'Edit post #{post_instance.pk}'
            },
            template_name='blog/post_form.html'
        )


@csrf_exempt
@require_POST
def like_post(request, id):
    """
    Increments post`s like field
    """
    result = False

    # Main logic
    post_obj = get_object_or_404(klass=models.Post, pk=id)
    post_obj.likes += 1
    post_obj.save()
    result = True

    # Response
    return JsonResponse({
        'result': result, 'likes': post_obj.likes
    })


class CreateCategory(PermissionRequiredMixin, CreateView):
    model = models.Category
    fields = (
        'name',
        'slug',
    )
    success_url = reverse_lazy('blog:show-all-posts')
    extra_context = {
        'page_title': 'Create a category'
    }
    permission_required = 'blog.add_category'


class UpdateCategory(PermissionRequiredMixin, UpdateView):
    model = models.Category
    fields = (
        'name',
        'slug',
    )
    success_url = reverse_lazy('blog:show-all-posts')
    permission_required = 'blog.change_category'


class ViewPost(DetailView):
    model = models.Post


class FilterPostByCategory(ListView):
    model = models.Post
    template_name = 'blog/all_posts.html'

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug', None)
        qs = super().get_queryset()
        qs = qs.filter(categories__slug=category_slug)
        return qs

HW9/Maktab50/djangol1/blog/templates/blog/all_posts.html
{% extends 'blog/base.html' %}
{% block content %}

    <div class="limiter">
        <div class="container-login100" style="background-color: #0f6674">
            <div class="row">

                <div class="col-3 m-b-4" style="color: white">
                    <h5 class="mb-2">Filter by category:</h5>
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:post-by-category' category.0 %}">{{ category.0 }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>

                <div class="row col-7">
                    {% for post in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                {% if post.intro_image %}
                                    <a href="{% url 'blog:detail' post.pk %}">
                                        <img class="card-img-top"
                                             src="{{ post.intro_image.url }}">
                                    </a>
                                {% endif %}
                                <div class="card-body">

                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text" style="color: #0056b3">{{ post.creator.first_name }}</small>
                                        <div class="btn-group">
                                            <button type="button"
                                                    class="btn btn-sm btn-outline-secondary text-danger like-btn"
                                                    data-post-id="{{ post.id }}">Like
                                                👍 (<span id="like-count-{{ post.id }}">{{ post.likes }})</span>
                                            </button>
                                        </div>
                                    </div>
                                    <p class="card-text mt-1">
                                        <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}: {{ post.content|truncatewords:12 }}</a>
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted mt-3">{{ post.created_data }}</small>
                                        {% if request.user.is_authenticated %}
                                            {% if post.creator == request.user %}
                                                <a href="{% url 'blog:edit' post.pk %}" type="button"
                                                   class="float-right mt-3">🖍</a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% for post in object_list_2 %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                {% if post.intro_image %}
                                    <a href="{% url 'blog:detail' post.pk %}">
                                        <img class="card-img-top"
                                             src="{{ post.intro_image.url }}">
                                    </a>
                                {% endif %}
                                <div class="card-body">

                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text" style="color: #0056b3">{{ post.creator.first_name }}</small>
                                        <div class="btn-group">
                                            <button type="button"
                                                    class="btn btn-sm btn-outline-secondary text-danger like-btn"
                                                    data-post-id="{{ post.id }}">Like
                                                👍 (<span id="like-count-{{ post.id }}">{{ post.likes }})</span>
                                            </button>
                                        </div>
                                    </div>
                                    <p class="card-text mt-1">
                                        <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}: {{ post.content|truncatewords:12 }}</a>
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted mt-3">{{ post.created_data }}</small>
                                        {% if request.user.is_authenticated %}
                                            {% if post.creator == request.user %}
                                                <a href="{% url 'blog:edit' post.pk %}" type="button"
                                                   class="float-right mt-3">🖍</a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}
{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('.like-btn').on('click', function (e) {
                var postId = $(e.target)[0].dataset.postId;
                $.ajax({
                    url: '/blog/like-post/' + postId,
                    method: 'POST',
                    success: function (response) {
                        var likes = response.likes;
                        $('#like-count-' + postId).html(likes);
                    }
                });
            });
        });
    </script>
{% endblock %}

{#<table class="table table-bordered table-dark">#}
{#        <thead>#}
{#                    <tr>#}
{#                        <th scope="col">title</th>#}
{#                        <th scope="col">data</th>#}
{#                        <th scope="col">FullName</th>#}
{#                        <th scope="col">Text</th>#}
{#                    </tr>#}
{#        </thead>#}
{#        {% for post in my_posts %}#}
{##}
{##}
{#                <tbody>#}
{#                    <tr>#}
{##}
{#                        <th scope="row">{{ post.title }}</th>#}
{#                        <td>{{ post.created_data }}</td>#}
{#                        <td>{{ post.creator.first_name }}{{ post.creator.last_name }}</td>#}
{#                        <td>{{ post.content }}</td>#}
{#                    </tr>#}
{#                </tbody>#}
{#        {% endfor %}#}
{##}
{#</table>#}

HW9/Maktab50/djangol1/blog/templates/blog/base.html
{% load static %}
<html lang="en">
<head>
    <title>
        My Blog:
        {% block page_header_title %}
            {{ page_title }}
        {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/util.css' %}" rel="stylesheet">
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <a class="navbar-brand" href={% url 'blog:show-all-posts' %}>Home</a>
    {% if perms.blog.add_post %}
        <a class="navbar-brand" href={% url 'blog:create-post' %}>Create Post</a>
    {% endif %}
    {% if perms.blog.add_category %}
        <a class="navbar-brand" href={% url 'blog:create-category' %}>Create Category</a>
    {% endif %}
    <a class="navbar-brand" href="{% url 'inventory:list' %}">Products</a>
    <ul class="navbar-nav ml-auto">
        {% if not user.is_authenticated %}
            <a class="navbar-brand" href={% url 'users:login' %}>Login</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="navbar-brand" style="color: #c80000" href={% url 'users:logout' %}>Logout</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'users:edit-profile' %}">{{ user.get_full_name }}</a>
        {% endif %}
    </ul>
</nav>

{# Django`s messages #}
<div class="container">
    <div class="col-12">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger">
                    {{ message }}
                    <button type="button" data-dismiss="alert" class="close">&times;</button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

{% block content %}YOUR CONTENT GOES HEAR{% endblock %}

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

{% block page_scripts %}{% endblock %}
<footer class="text-muted">
    <div class="container">
        <span class="text-muted align-content-center">Copyright &copy; {{ year }}</span>
        <p class="float-right">
            <a href="#" style="color: #005cbf">Back to top ⬆</a>
        </p>
    </div>
</footer>

</body>
</html>


{#<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>#}
{#<script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>#}
{#<script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>#}

HW9/Maktab50/djangol1/blog/templates/blog/category_form.html
{% extends 'blog/base.html' %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}

    <div class="limiter">
        <div class="container-login100" style="background-color: #0f6674">
            <div class="row mb-2">
                <form method="post">
                    {% csrf_token %}
                    <h3 style="color: dodgerblue" class="text mb-4">{{ page_title }}</h3>
                    {% with field=form.name %}
                        <div class="form-group">
                            <label for="{{ field.auto_id }}" style="color: white">{{ field.label }}</label>
                            <input type="text" id="{{ field.auto_id }}" class="form-control"
                                   value="{{ field.initial }}" name="{{ field.name }}">
                        </div>
                    {% endwith %}
                    {% with field=form.slug %}
                        <div class="form-group">
                            <label for="{{ field.auto_id }}" style="color: white">{{ field.label }}</label>
                            <input type="text" id="{{ field.auto_id }}" class="form-control"
                                   value="{{ field.initial }}" name="{{ field.name }}">
                        </div>
                    {% endwith %}
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

HW9/Maktab50/djangol1/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block page_header_title %}
    Post: {{ object.title }}
{% endblock %}
{% block content %}

    <div class="limiter">
        <div class="container-login100" style="background-color: #0f6674">
            <div class="row">
                {% if object.intro_image %}
                    <img class="col-6" src="{{ post.intro_image.url }}">
                {% endif %}

                <div class="col-6">
                    <div class="d-flex">
                        <h1 style="color: white" class="mb-4 mr-5">{{ object.title }}</h1>

                        {% if request.user.is_authenticated %}
                            {% if post.creator == request.user %}
                                <a href="{% url 'blog:edit' post.pk %}" type="button"
                                   class="float-right mt-3 ml-3">🖍</a>
                            {% endif %}
                        {% endif %}

                    </div>
                    <h3 style="color: white">Created by: {{ object.creator.get_full_name }}</h3>
                    <small class="text-muted mt-3" >{{ post.created_data }}</small>

                    <p style="color: white" class="mt-3">{{ object.content }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

HW9/Maktab50/djangol1/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}

    <div class="limiter">
        <div class="container-login100" style="background-color: #0f6674">
            <div class="row mb-2">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                <h3 style="color: dodgerblue" class="text mb-4">{{ page_title }}</h3>
                    <div class="form-group">
                        <label for="title" style="color: white">عنوان پست</label>
                        <input type="text" id="title" class="form-control" value="{{ form.initial.title }}" name="title">
                    </div>
                    <div class="form-group">
                        <label for="content" style="color: white">متن پست</label>
                        <textarea name="content" id="content" cols="50" rows="10" class="form-control">{{ form.initial.content }}</textarea>
                    </div>
                    <div style="color: white" class="form-group">
                        {{ form.intro_image }}
                        {% if form.instance.intro_image %}
                            <a href="{{ form.instance.intro_image.url }}">Current file</a>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.categories }}
                    </div>
{#                    <div class="form-group">#}
{#                        <label for="creator" style="color: white">کاربر ثبت کننده</label>#}
{#                        {{ form.creator }}#}
{#                        <select id="creator" name="creator" class="form-control">#}
{#                            <option value="1">Pourya</option>#}
{#                            <option value="2">Tom</option>#}
{#                            <option value="3">Rose</option>#}
{#                        </select>#}
{#                    </div>#}
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}